name: Wiki Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
- uses: actions/checkout@v4.1.1
- uses: Saber2pr/wiki-builder@v0.0.69
    title: MyBlog
    keywords: blog,js,html,css
    description: the what ever i dont know maybe save me from google
